# Generated by Django 3.1.7 on 2021-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile', models.IntegerField(blank=True)),
                ('event', models.CharField(max_length=64)),
            ],
        ),
    ]
